name: SimplisticEconomy
version: 1.1
main: net.megaplanet.simplisticeconomy.SimplisticEconomy
load: STARTUP
softdepend: [Vault]
api-version: 1.13
commands:
  pay:
  eco:
  money:
  bal:
  balance:
  balancetop:
  baltop:
  moneytop: